FROM python:3.9-slim

WORKDIR /app

COPY scripts/data_api.py /app/data_api.py
COPY env_credentials/.env.influxdb /app/.env

RUN pip install flask influxdb-client

EXPOSE 5001

CMD ["python", "data_api.py"]