FROM python:3.12-slim

WORKDIR /app

COPY services/data_api.py /app/data_api.py

RUN pip install fastapi uvicorn influxdb-client python-dotenv

EXPOSE 8000

CMD ["uvicorn", "data_api:app", "--host", "0.0.0.0", "--port", "8000"]