FROM python:3.9-slim

WORKDIR /app

COPY scripts/latency_api.py /app/latency_api.py
COPY env_credentials/.env.influxdb /app/.env

RUN pip install flask influxdb-client

EXPOSE 5000

CMD ["python", "latency_api.py"]